### ISSUE TITLE
Katoolin3 not installing any packages / tools

### ISSUE THREAD

**Issue by GeeAlex** [s-h-3-l-l/katoolin3#10]
Hello, I've set Katoolin3 up properly, however, when trying to install anything it simply takes a while to read package lists. Afterwards, it says 0 installed, 0 upgraded and 1400 not installed. 
It says successful afterwards, but no tool is actually installed.

Any ideas what may be causing this issue?

This is being installed as root on a Ubuntu Server 18.04 LTS system.

**Comment by s-h-3-l-l** [comment]
In commit 9395c9e298394ee28e660ad2ba35bda45894a435 I added more error messages. 
Please update your clone by executing ```sudo ./update.sh;```, run it again and show me the error messages.

**Comment by GeeAlex** [comment]
Updated it today, but changed the keyserver  to port 80 at "apt-key adv -qq --keyserver pool.sks-keyservers.net", as I don't have access to port 11371. A bunch of packages installed but some like nmap returned the error "you have held broken packages".

I'm just gonna apt-update and apt-upgrade then try install the rest.
