### ISSUE TITLE
libgstreamer-plugins-bad1.0-0_1.16.1-1+b1_amd64.deb and gstreamer1.0-plugins-bad_1.16.1-1+b1_amd64.deb conflict with the preinstalled ubuntu versions of themselves on Ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by KP2048** [s-h-3-l-l/katoolin3#11]
**Describe the bug**
libgstreamer-plugins-bad1.0-0_1.16.1-1+b1_amd64.deb and gstreamer1.0-plugins-bad_1.16.1-1+b1_amd64.deb conflict with the preinstalled ubuntu versions of themselves on Ubuntu 18.04.3 LTS
**To Reproduce**
1. Go to 'install all'
2. See error

**Expected behavior**
not conflict
**Screenshots**
https://pastebin.com/mR7yJbFm

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser Firefox
 - Version 18.04.3 LTS

**Comment by s-h-3-l-l** [comment]
Since errors like ```trying to overwrite '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstcamerabin.so', which is also in package gstreamer1.0-plugins-good:amd64 1.14.5-0ubuntu1~18.04.1``` state that a library already exists I don't consider this a bug with katoolin3 but a minor error with some dependencies that dont cause some tools to not be installed.
Because if I interpreted your logs correctly all tools have been successfully installed anyway.

If you get some errors outisde of katoolin3 now when using apt-get try the following to fix this (according to [askubuntu.com](https://askubuntu.com/questions/195950/trying-to-overwrite-usr-bin-opencv-haartraining-which-is-also-in-package-lib/430443#430443)):
```
sudo dpkg -P gstreamer1.0-plugins-bad:amd64;
sudo dpkg -P libgstreamer-plugins-bad1.0-0:amd64;
sudo apt-get install -f;
```

**Comment by KP2048** [comment]
I got things working, but now my WiFi is broken. It gets stuck at connecting

**Comment by KP2048** [comment]
I just did 
sudo apt-get install -f;
sudo dpkg --configure -a;
and things started working. 
Then my WiFi broke

**Comment by KP2048** [comment]
Sorry, it was
sudo apt-get clean;
sudo dpkg --configure -a;

**Comment by KP2048** [comment]
Also I can’t do dpkg -P <package>
Because those packages are system required.

**Comment by s-h-3-l-l** [comment]
I also got the Wifi problem once. 
Deleting the Wifi from the known networks and reconnecting (by entering the Wifi password again) solved it for me.

**Comment by KP2048** [comment]
Ok

**Comment by KP2048** [comment]
Btw I’m using this to make an Ubuntu flavor that includes all the kali Linux tools

**Comment by KP2048** [comment]
WiFi still not working

**Comment by s-h-3-l-l** [comment]
Hm, I added a disclaimer in commit 4149ab151d5ac052ac2e1f1eb1a61c605b092db3 that some packages might break the system.
I think uninstalling all tools would be the only way to restore the system.

**Comment by KP2048** [comment]
Do you know which ones?

**Comment by KP2048** [comment]
Or can you have the script tell you what packages will break things and or not install them?

**Comment by s-h-3-l-l** [comment]
> Do you know which ones?   

Try
```
aptitude why -v libgstreamer-plugins-bad1.0-0:amd64;
aptitude why -v gstreamer1.0-plugins-bad:amd64;
```
This prints a dependency tree with the specified packages as the root.
If you find a kali tool in there you know what caused the trouble.

> Or can you have the script tell you what packages will break things and or not install them?

No, then katoolin3 would become a full-blown package manager, which is not what I want.
