### ISSUE TITLE
Install Kali Menu did nothing

### ISSUE THREAD

**Issue by mrventer** [s-h-3-l-l/katoolin3#12]
Hi There,

I used option  6 ,  after the install I dont have the top right menu?

**Comment by s-h-3-l-l** [comment]
Do you use Ubuntu?

If so you maybe didn't have the ```classicmenu-indicator``` package installed.
See [this post](https://www.howtogeek.com/189929/how-to-install-and-launch-the-classic-gnome-menu-in-ubuntu-14.04/).

**Comment by s-h-3-l-l** [comment]
Since the author didn't respond within 14 days I am closing this issue now...
