### ISSUE TITLE
katoolin3 on clean Ubuntu 18.04 install leads to wifi issues after "Install All"

### ISSUE THREAD

**Issue by CollinLBauer** [s-h-3-l-l/katoolin3#15]
**Describe the bug**
Went to install all of the kali packages included in katoolin on my Ubuntu 18.04 install. After updating packages and rebooting, wifi consistently fails to connect to any 

**To Reproduce**
1. Install clean Ubuntu 18.04 install
2. Update Ubuntu packages
3. Install katoolin3
4. Install all katoolin packages
5. Update katoolin3 packages
6. Restart Ubuntu. Wifi will still detect networks, but cannot successfully connect to any.

**Expected behavior**
Wifi should still work.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
This is something I was trying for class. I'm honestly a total amateur when it comes to Linux, so it's entirely likely I likely missed an instruction or warning somewhere on the way.

**Comment by regiakb** [comment]
Same problem

**Comment by shreebles** [comment]
What do you mean by 5. Update katoolin3 packages?
When you install Packages with katoolin3, the latest versions are installed from the Kali repository.

Did you run a package manager / system update while katoolin3 was running?

If so, there is a disclaimer advising against doing that.

`DISCLAIMER:
Don't update your packages, upgrade your system or
modify your package cache in any other way while 
katoolin3 is still running!`

**Comment by amjeda** [comment]
Can I install katoolin3 with latest python 3.8.1?

**Comment by s-h-3-l-l** [comment]
@amjeda 
Not directly. katoolin3 uses the module 'apt' which is currently only available for python 3.7.4.
You would have to set PYTHONPATH to the directory containing 3.7.4 modules every time you run katoolin3 with python3.8.

**Comment by s-h-3-l-l** [comment]
@CollinLBauer, @regiakb
You are not the first one experiencing wifi issues.
Unfortunately I don't know which package causes those issues and
I am currently not able to analyze and find out.
I'll mark this as __unfixed__, sorry!

Also please note that the README explicitly states that you shouldn't install all tools at once on Ubuntu because this might break it.
