### ISSUE TITLE
W: Failed to fetch http://http.kali.org/kali/dists/kali-rolling/InRelease 503 Service Unavailable

### ISSUE THREAD

**Issue by erbeh77** [s-h-3-l-l/katoolin3#16]
> Main Menu
> 0) View Categories              
> 1) Install All                  
> 2) Uninstall All                
> 3) Search repository            
> 4) List installed packages      
> 5) List not installed packages  
> 6) Install Kali Menu            
> 7) Uninstall old katoolin       
> 8) Help                         
> 9) Exit 

> Reading package lists...
> Warning: Could not find package 'kali-menu'
> Nothing to install

**Comment by s-h-3-l-l** [comment]
Hm. What OS do you use?

'kali-menu' is still in the repos (https://http.kali.org/pool/main/k/kali-menu/) and
on debian buster installation of 'kali-menu' worked fine.

**Comment by erbeh77** [comment]
using ubuntu 18.04

**Comment by erbeh77** [comment]
Noticed this...

`W: Failed to fetch http://http.kali.org/kali/dists/kali-rolling/InRelease  503  Service Unavailable [IP: 192.99.200.113 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.
`

**Comment by s-h-3-l-l** [comment]
Since [http.kali.org](http://http.kali.org/kali/dists/kali-rolling/InRelease) redirects to other services based on your location I would suggest to try again every couple of hours. Maybe those services were down.

```
$ echo -e "GET /kali/dists/kali-rolling/InRelease HTTP/1.0\r\nHost: http.kali.org\r\n\r\n" | nc http.kali.org 80

HTTP/1.1 302 Found
[...]
X-MirrorBrain-Mirror: ftp.halifax.rwth-aachen.de
X-MirrorBrain-Realm: country
Link: <http://http.kali.org/kali/dists/kali-rolling/InRelease.meta4>; rel=describedby; type="application/metalink4+xml"
Link: <http://ftp.halifax.rwth-aachen.de/kali/dists/kali-rolling/InRelease>; rel=duplicate; pri=1; geo=de
Link: <http://ftp.belnet.be/pub/kali/kali/dists/kali-rolling/InRelease>; rel=duplicate; pri=2; geo=be
Link: <http://ftp2.nluug.nl/os/Linux/distr/kali/dists/kali-rolling/InRelease>; rel=duplicate; pri=3; geo=nl
Link: <http://ftp1.nluug.nl/os/Linux/distr/kali/dists/kali-rolling/InRelease>; rel=duplicate; pri=4; geo=nl
Link: <http://mirror.neostrada.nl/kali/dists/kali-rolling/InRelease>; rel=duplicate; pri=5; geo=nl
Location: http://ftp.halifax.rwth-aachen.de/kali/dists/kali-rolling/InRelease
[...]
```

**Comment by erbeh77** [comment]
tried it for several days - no go.  Issue still exist

**Comment by erbeh77** [comment]
it should be https, http won't work on the src
W: Failed to fetch http://http.kali.org/kali/dists/kali-rolling/InRelease 503 Service Unavailable [IP: 192.99.200.113 80]
