### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by RougeKek** [s-h-3-l-l/katoolin3#2]
I must admit I'm a little confused by the installation guide. 

chmod +x ./install.sh;
sudo ./install.sh;

those can in no way be the only two commands since you probably got to clone them. and other things
could I get a bit of Clarification on this?

**Comment by RougeKek** [comment]
actually, it was quite simple. so if I may I can just solve my own issue but I know there should be 1000's of ways to do this. I downloaded the zip file from here. which I unzipped `unzip katoolin3-master.zip` 

this created the folder in my Downloads folder 

and then the code is as simple as 
chmod +x 
./install.sh;
sudo ./install.sh;

**Comment by RougeKek** [comment]
done

**Comment by s-h-3-l-l** [comment]
I updated the README file with some clearer instructions how to install.
This should make it a bit easier :)
