### ISSUE TITLE
Please install the 'python-apt' package it's already installed though

### ISSUE THREAD

**Issue by RougeKek** [s-h-3-l-l/katoolin3#3]
**Describe the bug**
after the installation of the program the following message appears:"Successfully installed. Run it with 'katoolin3'." after then when typing in `katoolin3` the only message that appears is as above `Please install the 'python-apt' package

**To Reproduce**
Steps to reproduce the behavior: I'm not 100% sure this will reproduce it but I can't create it without it.
1. Download file (I downloaded via GUI/browser at: https://github.com/s-h-3-l-l/katoolin3)
2. navigate to folder with terminal, `unzip katoolin3-master.zip`
3. navigate into the now unpacked folder `sudo -i`/`sudo su`
4. `chmod +x ./install.sh`
5. (already root step 3) ./install.sh
6. `Executing: /tmp/apt-key-gpghome.Mvy6cn0xdS/gpg.1.sh --keyserver pool.sks-keyservers.net --recv-keys ED444FF07D8D0BF6
gpg: key ED444FF07D8D0BF6: 3 duplicate signatures removed
gpg: key ED444FF07D8D0BF6: 185 signatures not checked due to missing keys
gpg: key ED444FF07D8D0BF6: "Kali Linux Repository <devel@kali.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Successfully installed. Run it with 'katoolin3'.`
7.`cd` (optional)
8.`katoolin3` -> Please install the 'python-apt' package
9. exit root (ctrl+d)
10. sudo katoolin3 -> Please install the 'python-apt' package

**Expected behavior**
after the installation it should execute the katoolin 3 screen which allows me to download all the tools.

**Screenshots**
![katoolin3](https://user-images.githubusercontent.com/54829867/64482223-ac7c8d00-d1aa-11e9-8344-42565822b9bd.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 KTS
 - Browser Mozilla Firefox
 - Version 69.0 (64-bit)

**Comment by RougeKek** [comment]
I have not fixed the issue as such but for the time being I could at least access the program by navigating to the Dir. and then run python3 katoolin3.py which works like a charm. 

but I can still not access the program by just typing sudo Katoolin3

**Comment by s-h-3-l-l** [comment]
@RougeKek, thanks for the issue,

'python-apt' is the wrong package because it is only for python2.
'python3-apt' is the package that katoolin3 needs.

Try to install python3-apt and then it should work.

This was fixed in commit e2021a5008c4628fa198cb91f411c3a6ad12837e.

**Comment by RougeKek** [comment]
Yeah that works! Thanks so much
