### ISSUE TITLE
Can't install everything

### ISSUE THREAD

**Issue by xnetcat** [s-h-3-l-l/katoolin3#4]
Main Menu
0) View Categories
1) Install All
2) Uninstall All
3) Search repository
4) List installed packages
5) Update all Kali packages
6) Install Kali Menu
7) Uninstall old katoolin
8) Help
9) Exit

kat> 1

Install everything?
0) Yes
1) No

kat> 0
Reading package lists...
Warning: Could not find package 'pdgmail'
Warning: Could not find package 'automater'
Warning: Could not find package 'miranda'
Warning: Could not find package 'sslcaudit'
Warning: Could not find package 'wol-e'
Warning: Could not find package 'u3-pwn'
Warning: Could not find package 'keimpx'
Warning: Could not find package 'blindelephant'
Warning: Could not find package 'ua-tester'
Traceback (most recent call last):
  File "/usr/local/bin/katoolin3", line 1071, in <module>
    main()
  File "/usr/local/bin/katoolin3", line 1013, in main
    choice()
  File "/usr/local/bin/katoolin3", line 879, in install_all_packages
    APT.install(all_packages())
  File "/usr/local/bin/katoolin3", line 684, in install
    self._cache[pkg].mark_install()
  File "/usr/lib/python3/dist-packages/apt/package.py", line 1505, in mark_install
    fixer.resolve(True)
apt_pkg.Error: E:Unable to correct problems, you have held broken packages.

**Comment by s-h-3-l-l** [comment]
@kko7 thanks for the issue,

The program catches this error now and simply ignores it (only a warning will be issued).
Please update your repo clone with [update.sh](https://github.com/s-h-3-l-l/katoolin3/blob/master/update.sh) and then it should work.

This was fixed in commit feef8f261f2141342770de8efbbea660e05fe718.

**Comment by xnetcat** [comment]
Thanks, now it works
