### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by xnetcat** [s-h-3-l-l/katoolin3#5]
Setting up golismero (2.0-beta6+git20150114-0kali1) ...
Processing triggers for menu (2.1.47+b1) ...
Errors were encountered while processing:
 fern-wifi-cracker
E:Sub-process /usr/bin/dpkg returned an error code (1)
Install failed: installArchives() failed

**Comment by s-h-3-l-l** [comment]
Hm, this looks like an error with dpkg which I have no influence on.
